// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrA9oR6LAXNZvUuKoARtD6h9uI7BoA4o',
    appId: '1:59021085466:web:6308f3f59cd8ddbb9b3aa3',
    messagingSenderId: '59021085466',
    projectId: 'my-portifolio-ac6cd',
    authDomain: 'my-portifolio-ac6cd.firebaseapp.com',
    databaseURL: 'https://my-portifolio-ac6cd-default-rtdb.firebaseio.com',
    storageBucket: 'my-portifolio-ac6cd.appspot.com',
    measurementId: 'G-GKD3HQLX7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6e2wBBLZYarEdfTJn9SfGncfoCGH2H4',
    appId: '1:59021085466:android:8ac632dbe72511539b3aa3',
    messagingSenderId: '59021085466',
    projectId: 'my-portifolio-ac6cd',
    storageBucket: 'my-portifolio-ac6cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsELUABaQggIpubRriCI2u3dCr8sUUT3c',
    appId: '1:59021085466:ios:e68fcf78bfe51a9a9b3aa3',
    messagingSenderId: '59021085466',
    projectId: 'my-portifolio-ac6cd',
    storageBucket: 'my-portifolio-ac6cd.appspot.com',
    iosBundleId: 'com.example.myPortifolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsELUABaQggIpubRriCI2u3dCr8sUUT3c',
    appId: '1:59021085466:ios:e68fcf78bfe51a9a9b3aa3',
    messagingSenderId: '59021085466',
    projectId: 'my-portifolio-ac6cd',
    databaseURL: 'https://my-portifolio-ac6cd-default-rtdb.firebaseio.com',
    storageBucket: 'my-portifolio-ac6cd.appspot.com',
    iosBundleId: 'com.example.myPortifolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIrA9oR6LAXNZvUuKoARtD6h9uI7BoA4o',
    appId: '1:59021085466:web:fd4b09884d59acac9b3aa3',
    messagingSenderId: '59021085466',
    projectId: 'my-portifolio-ac6cd',
    authDomain: 'my-portifolio-ac6cd.firebaseapp.com',
    databaseURL: 'https://my-portifolio-ac6cd-default-rtdb.firebaseio.com',
    storageBucket: 'my-portifolio-ac6cd.appspot.com',
    measurementId: 'G-NQYN29WPME',
  );
}
